# Generated by Django 4.2.7 on 2024-04-21 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.classmodel')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.countriesmodel')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.departmentsmodel')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.statusmodel')),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.universitiesmodel')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
