# Generated by Django 5.1.1 on 2024-09-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformationmodel',
            name='living_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='living_city', to='inputs.countriesmodel'),
        ),
        migrations.AlterField(
            model_name='additionalinformationmodel',
            name='living_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='living_country', to='inputs.countriesmodel'),
        ),
    ]
