# Generated by Django 4.2.7 on 2024-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_class_educationalinformationmodel_grande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalinformationmodel',
            name='Grande',
        ),
    ]
