# Generated by Django 5.1.1 on 2024-09-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_privacymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacymodel',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
