# Generated by Django 5.1.1 on 2024-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_privacymodel_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacymodel',
            name='message_privacy',
            field=models.CharField(default='everyone', max_length=20),
        ),
    ]
