# Generated by Django 4.2.7 on 2024-04-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_additionalinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalInformation',
            new_name='AdditionalInformationModel',
        ),
    ]
