# Generated by Django 4.2.6 on 2024-07-28 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0011_alter_educationalinformationmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
