# Generated by Django 4.2.6 on 2024-07-28 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inputs', '0004_delete_grandemodel'),
        ('profiles', '0012_alter_educationalinformationmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='Country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inputs.countriesmodel'),
        ),
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='Department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inputs.departmentsmodel'),
        ),
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='Status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inputs.statusmodel'),
        ),
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='University',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inputs.universitiesmodel'),
        ),
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
