# Generated by Django 4.2.6 on 2024-07-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0004_delete_grandemodel'),
        ('profiles', '0013_alter_educationalinformationmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.countriesmodel'),
        ),
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.departmentsmodel'),
        ),
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.statusmodel'),
        ),
        migrations.AlterField(
            model_name='educationalinformationmodel',
            name='University',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.universitiesmodel'),
        ),
    ]
