# Generated by Django 4.2.7 on 2024-04-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalinformationmodel',
            old_name='Class',
            new_name='Grande',
        ),
    ]
