# Generated by Django 4.2.6 on 2024-04-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profilepicturemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePictureModel',
        ),
    ]
