# Generated by Django 5.0.7 on 2024-08-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0006_alter_city_country_delete_country'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.city'),
        ),
        migrations.AddField(
            model_name='marketplacemodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.countriesmodel'),
        ),
    ]
