# Generated by Django 5.1.1 on 2024-09-19 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMarketPlaceFilterModel',
            new_name='MarketPlaceFilterModel',
        ),
    ]
