# Generated by Django 5.0.7 on 2024-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplacemodel_city_marketplacemodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
