# Generated by Django 5.1.1 on 2024-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_usermarketplacefiltermodel_marketplacefiltermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
