# Generated by Django 5.0.7 on 2024-08-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplacemodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
    ]
