# Generated by Django 5.1.1 on 2024-09-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_marketplacemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacefiltermodel',
            name='following_only',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
