# Generated by Django 5.0.7 on 2024-08-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0007_currency'),
        ('marketplace', '0004_marketplacemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.currency'),
        ),
    ]
