# Generated by Django 5.0.7 on 2024-08-28 11:06

import apps.marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_marketplaceimagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceimagesmodel',
            name='image',
            field=models.ImageField(upload_to=apps.marketplace.models.upload_to),
        ),
    ]
