# Generated by Django 4.2.6 on 2024-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_marketplaceimagesmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacemodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
