# Generated by Django 4.2.6 on 2024-09-04 20:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_marketplacemodel_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacemodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
