# Generated by Django 4.2.7 on 2024-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_educationalinformationmodel_grande'),
        ('inputs', '0003_alter_grandemodel_grande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrandeModel',
        ),
    ]
