# Generated by Django 5.0.7 on 2024-08-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_country_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.countriesmodel'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
