# Generated by Django 5.1.1 on 2025-03-02 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Şikayet', 'verbose_name_plural': 'Şikayetler'},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='reason',
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam/Istenmeyen İçerik'), ('nudity', 'Müstehcen İçerik'), ('hate', 'Nefret Söylemi'), ('violence', 'Şiddet İçeriği'), ('harassment', 'Taciz'), ('false', 'Yanlış Bilgi'), ('other', 'Diğer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('under_review', 'İncelemede'), ('resolved', 'Çözüldü'), ('rejected', 'Reddedildi')], default='pending', max_length=13),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['content_type', 'object_id'], name='complaints__content_a52642_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints__created_805464_idx'),
        ),
    ]
