# Generated by Django 5.1.1 on 2024-09-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confessionsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
