# Generated by Django 5.0.7 on 2024-08-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessionsmodel',
            name='is_privacy',
            field=models.BooleanField(default=True),
        ),
    ]
