# Generated by Django 4.2.6 on 2024-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_confessionsmodel_is_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessionsmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
