# Generated by Django 5.0.7 on 2024-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
