# Generated by Django 5.1.1 on 2024-09-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
        ('post', '0002_postsfiltermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsfiltermodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.countriesmodel'),
        ),
    ]
