# Generated by Django 5.0.7 on 2024-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_imagemodel_delete_postimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
