# Generated by Django 5.1.1 on 2024-09-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postsphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsfiltermodel',
            name='following_only',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
