# Generated by Django 5.1.1 on 2024-09-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postsfiltermodel_following_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='content',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
