# Generated by Django 5.1.1 on 2024-09-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postsmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='content',
            field=models.TextField(blank=True, max_length=360, null=True),
        ),
    ]
