# Generated by Django 4.2.6 on 2024-07-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_postcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
