# Generated by Django 5.0.7 on 2024-07-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_delete_postcomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
