# Generated by Django 4.2.6 on 2024-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
