# Generated by Django 5.1.1 on 2024-09-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='content',
            field=models.TextField(),
        ),
    ]
