# Generated by Django 4.2.6 on 2024-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent_folder',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
    ]
