# Generated by Django 5.0.7 on 2024-09-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsmodel_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsmodel',
            options={'verbose_name': 'Doküman', 'verbose_name_plural': 'Dokümanlar'},
        ),
    ]
