# Generated by Django 5.1.1 on 2024-09-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentsmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentsfiltermodel',
            name='following_only',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
