# Generated by Django 4.2.6 on 2024-08-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_parent_folder_folder_parent_alter_folder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
    ]
