# Generated by Django 4.2.6 on 2024-08-24 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_document_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentsModel',
        ),
        migrations.RenameModel(
            old_name='Folder',
            new_name='FolderModel',
        ),
    ]
