# Generated by Django 4.2.6 on 2024-09-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_userdocumentsfiltermodel_delete_userdocumentsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsmodel',
            old_name='uploaded_at',
            new_name='create_at',
        ),
    ]
