# Generated by Django 5.1.1 on 2024-09-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiltermodel',
            name='following_only',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
