# Generated by Django 5.0.7 on 2024-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_articlesmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
    ]
