# Generated by Django 4.2.6 on 2024-08-26 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_articlesmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='futured_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blogs/'),
            preserve_default=False,
        ),
    ]
