# Generated by Django 5.0.7 on 2024-08-27 06:52

import apps.blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_articlesmodel_futured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='futured_image',
            field=models.ImageField(upload_to=apps.blogs.models.upload_to),
        ),
    ]
