# Generated by Django 5.0.7 on 2024-09-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_userfiltermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiltermodel',
            name='created_at_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfiltermodel',
            name='created_at_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
