# Generated by Django 5.0.7 on 2024-09-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_userfiltermodel_created_at_end_and_more'),
        ('inputs', '0007_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfiltermodel',
            name='created_at_end',
        ),
        migrations.RemoveField(
            model_name='userfiltermodel',
            name='created_at_start',
        ),
        migrations.AddField(
            model_name='userfiltermodel',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.universitiesmodel'),
        ),
    ]
