# Generated by Django 5.0.7 on 2024-09-03 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_userfiltermodel_department'),
        ('inputs', '0007_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiltermodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inputs.statusmodel'),
        ),
    ]
