# Generated by Django 5.0.7 on 2024-09-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_userfiltermodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiltermodel',
            name='order_by',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
