# Generated by Django 4.2.6 on 2024-09-03 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0007_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0013_userfiltermodel_order_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFilterModel',
            new_name='FilterModel',
        ),
    ]
