# Generated by Django 5.0.7 on 2024-09-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_rename_userfiltermodel_filtermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesmodel',
            options={'ordering': ['-create_at']},
        ),
    ]
