# Generated by Django 4.2.6 on 2024-09-04 16:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_userfiltermodel_delete_filtermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiltermodel',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.category'),
        ),
    ]
