# Generated by Django 4.2.7 on 2024-04-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CountriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Countries', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='UniversitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Universities', models.CharField(max_length=255)),
                ('Countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.countriesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departments', models.CharField(max_length=255)),
                ('Universities', models.ManyToManyField(to='inputs.universitiesmodel')),
            ],
        ),
    ]
