# Generated by Django 4.2.7 on 2024-04-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_class_educationalinformationmodel_grande'),
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassModel',
            new_name='GrandeModel',
        ),
        migrations.RenameField(
            model_name='grandemodel',
            old_name='Class',
            new_name='Grande',
        ),
    ]
