# Generated by Django 4.2.7 on 2024-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_rename_classmodel_grandemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandemodel',
            name='Grande',
            field=models.CharField(max_length=55),
        ),
    ]
