# Generated by Django 5.1.1 on 2024-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
