# Generated by Django 5.1.1 on 2024-09-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
