# Generated by Django 5.1.1 on 2024-09-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_followrequest_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_read',
        ),
    ]
