# Generated by Django 5.1.1 on 2024-09-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_object_id',
        ),
    ]
